### ISSUE TITLE
Add description of recommendation category and evidence type

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/opioid-cds-r4#232] opened 2022-10-27 16:51 UTC
The 2016 Opioid Prescribing Guideline establishes recommendation category and evidence type for each recommendation, and provides definitions and explanatory text for the categorization and meaning of each evidence type. Provide links from the recommendation category and evidence type in each recommendation to a discussion of those summarizing (and linking directly to) the discussion in the guideline.

**Comment by brynrhodes** [comment] 2022-10-31 17:57
Also double-check that the extensions on each recommendation correctly reflect the guideline categorization and evidenceType (strength-of-recommendation and quality-of-evidence)

**Comment by alackerbauer** [comment] 2023-03-22 09:50
is this a duplicate of #268 ?

**Comment by c-schuler** [comment] 2023-03-23 20:55
@alackerbauer Sorry for the confusion. This is not a duplicate, but it is hard to tell. The milestone indicates that this issue refers to the 2016 branch. Whereas #268 is for the master branch.

**Comment by c-schuler** [comment] 2023-03-23 21:12
Resolved in #310

**Closed by c-schuler** 2023-03-23 21:12 UTC
Labels: documentation, 2
