### ISSUE TITLE
Add a link to the Opioid Value Set Generator to the vocabulary readme

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/opioid-cds-r4#234] opened 2022-10-31 17:34 UTC
Opioid Value Set generator is documented in Tooling:
https://github.com/cqframework/cqf-tooling/blob/master/tooling/src/main/java/org/opencds/cqf/tooling/terminology/templateToValueSetGenerator/README.md

Need to add a link and the step-by-step instructions for refreshing terminology to the vocabulary folder here

**Comment by c-schuler** [comment] 2023-03-15 18:39
duplicate of #142 and #143

**Closed by c-schuler** 2023-03-15 18:39 UTC
Labels: documentation
