### ISSUE TITLE
Review test cases 2 and 5 for Recommendation 8, consider their intentions and how to update them accordingly

### ISSUE THREAD

**Issue by bryantaustin13** [cqframework/opioid-cds-r4#248] opened 2022-11-04 14:34 UTC
CU Recommendation 8 IG Feedback Action Item

Was OPD_55

**Comment by c-schuler** [comment] 2023-03-15 19:06
Closing this as it is too poorly defined to be useful. Will consider reopening once/if the issue is made more clear

**Closed by c-schuler** 2023-03-15 19:06 UTC
